/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Principal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MI EQUIPO
 */
public class jPanelInicioMaterias extends javax.swing.JPanel {

    public jPanelInicioMaterias() {
        initComponents();
         
    }
public void cargarMateriasEnTabla() {
    String ruta = "C:\\Users\\MI EQUIPO\\Desktop\\Trabajos U\\Simulacion de Sistemas\\Task Manager\\materias.txt";
    DefaultTableModel modelo = (DefaultTableModel) tblListaMateriasJPanelInicioMaterias.getModel();
    modelo.setRowCount(0); // Limpiar la tabla

    try (BufferedReader reader = new BufferedReader(new FileReader(ruta))) {
        String linea;

        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length == 2) {
                modelo.addRow(new Object[]{datos[0], datos[1]}); // Nombre y Descripción
            }
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar las materias: " + e.getMessage());
    }

    tblListaMateriasJPanelInicioMaterias.revalidate();
    tblListaMateriasJPanelInicioMaterias.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnEliminarJPanelInicioMaterias = new javax.swing.JButton();
        btnEditarJPanelInicioMaterias = new javax.swing.JButton();
        btnCrearNuevoJPanelInicioMaterias = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaMateriasJPanelInicioMaterias = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("Buscar...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 142, 300, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoFiltro.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 30, 30));

        btnEliminarJPanelInicioMaterias.setText("Eliminar");
        btnEliminarJPanelInicioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJPanelInicioMateriasActionPerformed(evt);
            }
        });
        add(btnEliminarJPanelInicioMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 90, -1));

        btnEditarJPanelInicioMaterias.setText("Editar");
        add(btnEditarJPanelInicioMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 100, -1));

        btnCrearNuevoJPanelInicioMaterias.setText("Crear Nuevo");
        btnCrearNuevoJPanelInicioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevoJPanelInicioMateriasActionPerformed(evt);
            }
        });
        add(btnCrearNuevoJPanelInicioMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Materias");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, 50));

        tblListaMateriasJPanelInicioMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre de la Matera", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tblListaMateriasJPanelInicioMaterias);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 310, 220));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bienvenido!");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 220, 60));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoListas.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 520, 320));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manager");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Task");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoTotal.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -1, 690, 560));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearNuevoJPanelInicioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevoJPanelInicioMateriasActionPerformed
        // Obtener el JFrame contenedor
    InterfazInicioMaterias interfazInicioMaterias = (InterfazInicioMaterias) SwingUtilities.getWindowAncestor(this);
    
    // Obtener el panel jPanelInicioMaterias desde el JFrame
    jPanelInicioMaterias panel = interfazInicioMaterias.getjPanelInicioMaterias();

    // Pasar el panel al constructor
    CrearNuevoListaMaterias nuevaMateria = new CrearNuevoListaMaterias(panel);
    nuevaMateria.setVisible(true);
    }//GEN-LAST:event_btnCrearNuevoJPanelInicioMateriasActionPerformed

    private void btnEliminarJPanelInicioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJPanelInicioMateriasActionPerformed
         int selectedRow = tblListaMateriasJPanelInicioMaterias.getSelectedRow();  
    if (selectedRow == -1) {  
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una materia para eliminar.");
        return;
    }

    // Aquí accedes a la columna 0 porque es donde está el nombre de la materia
    String nombreMateriaSeleccionada = (String) tblListaMateriasJPanelInicioMaterias.getValueAt(selectedRow, 0);
    
    // Eliminar la fila de la tabla
    DefaultTableModel modelo = (DefaultTableModel) tblListaMateriasJPanelInicioMaterias.getModel();
    modelo.removeRow(selectedRow);
    
    // Eliminar la materia del archivo
    eliminarMateriaDelArchivo(nombreMateriaSeleccionada);

    // Volver a cargar las materias en la tabla después de la eliminación
    cargarMateriasEnTabla();  
}

private void eliminarMateriaDelArchivo(String nombreMateria) {
    String ruta = "C:\\Users\\MI EQUIPO\\Desktop\\Trabajos U\\Simulacion de Sistemas\\Task Manager\\materias.txt";  
    File archivo = new File(ruta);

    List<String> lineasRestantes = new ArrayList<>();
    
    try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
        String linea;
        
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(";");

            if (datos.length >= 2) {
                // Compara con el nombre de la materia (columna 0)
                if (!datos[0].equals(nombreMateria)) {  
                    lineasRestantes.add(linea);
                }
            }
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {
            for (String l : lineasRestantes) {
                writer.write(l);
                writer.newLine();
            }
        }

        JOptionPane.showMessageDialog(this, "Materia eliminada correctamente.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar la materia: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEliminarJPanelInicioMateriasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearNuevoJPanelInicioMaterias;
    private javax.swing.JButton btnEditarJPanelInicioMaterias;
    private javax.swing.JButton btnEliminarJPanelInicioMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblListaMateriasJPanelInicioMaterias;
    // End of variables declaration//GEN-END:variables
}
