/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MI EQUIPO
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        btnSalirContraseña = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnRegistrarseRegistrarse = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        passwordFieldConfirmarContraseñaContraseña = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        passwordFieldContraseñaContraseña = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txtEmailRegistrarse = new javax.swing.JTextField();
        txtNombreUsuarioRegistrarse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Salir");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        btnSalirContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBotones.png"))); // NOI18N
        btnSalirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 70, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Registrarse");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        btnRegistrarseRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBotones.png"))); // NOI18N
        btnRegistrarseRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarseRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 100, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Confirmar Contraseña");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Contraseña");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre de Usuario");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 160, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 70, -1));

        passwordFieldConfirmarContraseñaContraseña.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(passwordFieldConfirmarContraseñaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 190, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoContraseña.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 30, 30));

        passwordFieldContraseñaContraseña.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(passwordFieldContraseñaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 190, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoContraseña.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 30, 30));

        txtEmailRegistrarse.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtEmailRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, -1));

        txtNombreUsuarioRegistrarse.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtNombreUsuarioRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 190, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoEmail.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoEmail.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 30, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 43)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registrarse");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 240, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoRegistrarse.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 300, 290));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manager");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS PGothic", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Task");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 100, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoTaskManagerMINIATURA.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoListas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 500, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoISyRegistrarse.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoTotal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manager");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirContraseñaActionPerformed
         IniciarSesion ventanaLogin = new IniciarSesion();
        ventanaLogin.setVisible(true);
        dispose(); // cerrar la ventana de registro
    }//GEN-LAST:event_btnSalirContraseñaActionPerformed

    private void btnRegistrarseRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseRegistrarseActionPerformed
         String email = txtEmailRegistrarse.getText().trim();
        String nombreUsuario = txtNombreUsuarioRegistrarse.getText().trim();
        String contraseña = new String(passwordFieldContraseñaContraseña.getPassword()).trim();
        String confirmarContraseña = new String(passwordFieldConfirmarContraseñaContraseña.getPassword()).trim();

        // Verificar que no haya campos vacíos
        if (email.isEmpty() || nombreUsuario.isEmpty() || contraseña.isEmpty() || confirmarContraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
            return;
        }

        // Verificar que las contraseñas coincidan
        if (!contraseña.equals(confirmarContraseña)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            return;
        }

        // Verificar si el correo ya está registrado
        File archivo = new File("usuarios.txt");
        if (archivo.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
                String linea;
                while ((linea = reader.readLine()) != null) {
                    String[] partes = linea.split(",");
                    if (partes.length >= 1 && partes[0].equalsIgnoreCase(email)) {
                        JOptionPane.showMessageDialog(null, "Este correo ya está registrado.");
                        return;
                    }
                }
            } catch (FileNotFoundException ex) {
                 Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(Registrarse.class.getName()).log(Level.SEVERE, null, ex);
             }        }

        // Guardar usuario en el archivo
try (FileWriter writer = new FileWriter(archivo, true)) {
    writer.write(email + "," + nombreUsuario + "," + contraseña + "\n");
    JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente.");

    // Limpiar los campos
    txtEmailRegistrarse.setText("");
    txtNombreUsuarioRegistrarse.setText("");
    passwordFieldContraseñaContraseña.setText("");
    passwordFieldConfirmarContraseñaContraseña.setText("");

    // Abrir interfaz de IniciarSesion
    IniciarSesion login = new IniciarSesion();
    login.setVisible(true);
    dispose(); // cerrar la ventana de registro

} catch (IOException ex) {
    JOptionPane.showMessageDialog(null, "Error al guardar el usuario: " + ex.getMessage());
}
    
    }//GEN-LAST:event_btnRegistrarseRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarseRegistrarse;
    private javax.swing.JButton btnSalirContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField passwordFieldConfirmarContraseñaContraseña;
    private javax.swing.JPasswordField passwordFieldContraseñaContraseña;
    private javax.swing.JTextField txtEmailRegistrarse;
    private javax.swing.JTextField txtNombreUsuarioRegistrarse;
    // End of variables declaration//GEN-END:variables
}
